sudo: required

services:
  - docker

install:
  - docker build --build-arg AMPACHE_VERSION=$AMPACHE_VERSION --tag ampache_image .

script:
  - docker images | grep ampache_image
  - docker run -d --name=ampache_container -p 1234:80 ampache_image
  - docker ps | grep ampache_container

env:
  - AMPACHE_VERSION=3.8.8
  - AMPACHE_VERSION=3.9.0
  - AMPACHE_VERSION=master
