---
version: "3"
services:
  ampache:
    environment:
      - AMPACHE_VERSION
    build: 
      context: .
      args:
        AMPACHE_VERSION: $AMPACHE_VERSION
    image: c4pr1c3/ampache:$AMPACHE_VERSION
    container_name: ampache-$AMPACHE_VERSION
    volumes:
      - ./music:/media
      - ./db:/var/lib/mysql
    ports:
      - 8090:80
