---
version: "3"
services:
  ampache:
    build: 
      context: .
      args:
        AMPACHE_VERSION: 3.9.0
    image: c4pr1c3/ampache:$AMPACHE_VERSION
    container_name: ampache
    volumes:
      - ./music:/media:ro
      - ./db:/var/lib/mysql
      - ./mysql:/etc/mysql
      - ./www:/var/www
    ports:
      - 8090:80
