#!/usr/bin/env sh
# https://github.com/docker/hub-feedback/issues/508
# https://github.com/jnovack/dockerhub-hooks/blob/master/hooks/build
# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

docker build \
            --build-arg AMPACHE_VERSION=3.9.0 \
            -t $IMAGE_NAME .

